#!/bin/bash
#
#Common variables

RANDOM_STRING=$(tr -dc a-z </dev/urandom | head -c 4)

# Primus Company project related variables
export PRIMUS_PROJECT_REGION=${PRIMUS_PROJECT_REGION:-'us-west1'}
export PRIMUS_PROJECT_ZONE=${PRIMUS_PROJECT_ZONE:-'us-west1-b'}
export PRIMUS_PROJECT_LOCATION=${PRIMUS_PROJECT_LOCATION:-'global'}

# Primus Company resource related variables
export PRIMUS_INPUT_STORAGE_BUCKET=${PRIMUS_INPUT_STORAGE_BUCKET:-${PRIMUS_PROJECT_ID}-input-bucket}
export PRIMUS_SERVICEACCOUNT=${PRIMUS_SERVICEACCOUNT:-primus-sa}
export PRIMUS_WIP_PROVIDER=${PRIMUS_WIP_PROVIDER:-primus-wip-provider}
export PRIMUS_WORKLOAD_IDENTITY_POOL=${PRIMUS_WORKLOAD_IDENTITY_POOL:-primus-wip}
export PRIMUS_ARTIFACT_REPOSITORY=${PRIMUS_ARTIFACT_REPOSITORY:-${PRIMUS_PROJECT_ID}-artifact-repo}
export PRIMUS_PROJECT_REPOSITORY_REGION=${PRIMUS_PROJECT_REPOSITORY_REGION:-'us'}

# Secundus Company project related variables
export SECUNDUS_PROJECT_REGION=${SECUNDUS_PROJECT_REGION:-'us-west1'}
export SECUNDUS_PROJECT_ZONE=${SECUNDUS_PROJECT_ZONE:-'us-west1-b'}
export SECUNDUS_PROJECT_LOCATION=${SECUNDUS_PROJECT_LOCATION:-'global'}
export SECUNDUS_PROJECT_REPOSITORY_REGION=${SECUNDUS_PROJECT_REPOSITORY_REGION:-'us'}

# Secundus Company resource related variables
export SECUNDUS_INPUT_STORAGE_BUCKET=${SECUNDUS_INPUT_STORAGE_BUCKET:-${SECUNDUS_PROJECT_ID}-input-bucket}
export SECUNDUS_SERVICEACCOUNT=${SECUNDUS_SERVICEACCOUNT:-${SECUNDUS_PROJECT_ID}-sa}
export SECUNDUS_RESULT_STORAGE_BUCKET=${SECUNDUS_RESULT_STORAGE_BUCKET:-${SECUNDUS_PROJECT_ID}-result-bucket}

# Workload related variables
export WORKLOAD_SERVICEACCOUNT=${WORKLOAD_SERVICEACCOUNT:-workload-sa}
export WORKLOAD_IMAGE_NAME=${WORKLOAD_IMAGE_NAME:-workload-container}
export WORKLOAD_IMAGE_TAG=${WORKLOAD_IMAGE_TAG:-latest}
export WORKLOAD_VM=${WORKLOAD_VM:-workload-vm}