#!/bin/bash
#
#Common variables

RANDOM_STRING=$(tr -dc a-z </dev/urandom | head -c 4)

# Primus Bank project related variables
export PRIMUS_PROJECT_REGION=${PRIMUS_PROJECT_REGION:-'us-west1'}
export PRIMUS_PROJECT_ZONE=${PRIMUS_PROJECT_ZONE:-'us-west1-b'}
export PRIMUS_PROJECT_LOCATION=${PRIMUS_PROJECT_LOCATION:-'global'}

# Primus Bank resource related variables
export PRIMUS_INPUT_STORAGE_BUCKET=${PRIMUS_INPUT_STORAGE_BUCKET:-${PRIMUS_PROJECT_ID}-input-bucket}
export PRIMUS_ENC_KEY=${PRIMUS_ENC_KEY:-${PRIMUS_PROJECT_ID}-enc-key-${RANDOM_STRING}}
export PRIMUS_ENC_KEYRING=${PRIMUS_ENC_KEYRING:-${PRIMUS_PROJECT_ID}-enc-kr}
export PRIMUS_SERVICE_ACCOUNT=${PRIMUS_SERVICE_ACCOUNT:-${PRIMUS_PROJECT_ID}-sa}
export PRIMUS_WIP_PROVIDER=${PRIMUS_WIP_PROVIDER:-${PRIMUS_PROJECT_ID}-wip-provider}
export PRIMUS_WORKLOAD_IDENTITY_POOL=${PRIMUS_WORKLOAD_IDENTITY_POOL:-${PRIMUS_PROJECT_ID}-wip}
export PRIMUS_ARTIFACT_REPOSITORY=${PRIMUS_ARTIFACT_REPOSITORY:-${PRIMUS_PROJECT_ID}-artifact-repo}
export PRIMUS_PROJECT_REPOSITORY_REGION=${PRIMUS_PROJECT_REPOSITORY_REGION:-'us'}


# Secundus Bank project related variables
export SECUNDUS_PROJECT_REGION=${SECUNDUS_PROJECT_REGION:-'us-west1'}
export SECUNDUS_PROJECT_ZONE=${SECUNDUS_PROJECT_ZONE:-'us-west1-b'}
export SECUNDUS_PROJECT_LOCATION=${SECUNDUS_PROJECT_LOCATION:-'global'}

# Secundus Bank resource related variables
export SECUNDUS_INPUT_STORAGE_BUCKET=${SECUNDUS_INPUT_STORAGE_BUCKET:-${SECUNDUS_PROJECT_ID}-input-bucket}
export SECUNDUS_ENC_KEY=${SECUNDUS_ENC_KEY:-${SECUNDUS_PROJECT_ID}-enc-key-${RANDOM_STRING}}
export SECUNDUS_ENC_KEYRING=${SECUNDUS_ENC_KEYRING:-${SECUNDUS_PROJECT_ID}-enc-kr}
export SECUNDUS_SERVICE_ACCOUNT=${SECUNDUS_SERVICE_ACCOUNT:-${SECUNDUS_PROJECT_ID}-sa}
export SECUNDUS_WIP_PROVIDER=${SECUNDUS_WIP_PROVIDER:-${SECUNDUS_PROJECT_ID}-wip-provider}
export SECUNDUS_WORKLOAD_IDENTITY_POOL=${SECUNDUS_WORKLOAD_IDENTITY_POOL:-${SECUNDUS_PROJECT_ID}-wip}
export SECUNDUS_RESULT_STORAGE_BUCKET=${SECUNDUS_RESULT_STORAGE_BUCKET:-${SECUNDUS_PROJECT_ID}-result-bucket}

# Workload related variables
export WORKLOAD_SERVICE_ACCOUNT=${WORKLOAD_SERVICE_ACCOUNT:-workload-sa}
export WORKLOAD_IMAGE_NAME=${WORKLOAD_IMAGE_NAME:-workload-container}
export WORKLOAD_IMAGE_TAG=${WORKLOAD_IMAGE_TAG:-latest}